<?php


namespace models;

/**
 * @property string $name
 * @property string $value
*/
class Input extends Control
{
    private $name;
    private $value;
    private $placeholder;

    public function __construct( $name, $value, $width, $height, $background, $placeholder)
    {
        parent::__construct($width, $height, $background); // TODO: Change the autogenerated stub
        $this->setName($name);
        $this->setValue($value);
        $this->setPlaceholder($placeholder);
    }

    /**
     * @return mixed
     */
    public function getPlaceholder()
    {
        return $this->placeholder;
    }

    /**
     * @param mixed $placeholder
     */
    public function setPlaceholder($placeholder)
    {
        $this->placeholder = $placeholder;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * @param mixed $value
     */
    public function setValue($value)
    {
        $this->value = $value;
    }

    public function toHTML()
    {
        ob_start();
        include "views\\input.php";
        return ob_get_clean();

    }



}